services:   
  app:
    image: python:3.12-slim
    volumes:
      - ./app:/workspace
      - ./pip-cache:/root/.cache/pip
    ports:
      - "443:443"
    working_dir: /workspace
    command: >
      sh -c "
        if [ ! -f /workspace/venv/bin/activate ]; then python -m venv /workspace/venv; fi &&
        . /workspace/venv/bin/activate &&
        pip install -r requirements.txt &&
        if [ ! -f /workspace/cert.pem ] || [ ! -f /workspace/key.pem ]; then
          openssl req -x509 -newkey rsa:4096 -keyout /workspace/key.pem -out /workspace/cert.pem -days 365 -nodes -subj '/CN=localhost'
        fi &&
        python run.py
      "
volumes:
  pip-cache:
